#!/usr/bin/env python3
"""Generate the provider matrix from committed, validated evidence.

The shared 4a/4b mock suites describe WanCode's OpenAI-compatible transport
contract. They are not provider-specific live verification. Provider rows use a
separate VERIFIED/PARTIAL/NOT-RUN status, and every non-NOT-RUN row must link to
an existing committed file under docs/.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path, PurePosixPath
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
EVIDENCE = DOCS / "evidence"
SOURCES = DOCS / "provider-compat-sources.json"
OUT = DOCS / "provider-compatibility.md"
VALID_STATUSES = {"VERIFIED", "PARTIAL", "NOT-RUN"}

HEADER = """<!-- GENERATED by scripts/gen_compat_matrix.py — do not edit by hand.
     Sources: docs/evidence/compliance-summary-*.json + docs/provider-compat-sources.json.
     Regenerate: python scripts/gen_compat_matrix.py (CI enforces freshness). -->
# Provider compatibility matrix

“OpenAI-compatible” is split into two evidence classes:

1. **Shared mock contract** — suites 4a/4b exercise WanCode's transport,
   streaming, error, tool-call, and multimodal boundaries against scenario
   fixtures. These results are provider-agnostic and must not be presented as a
   live run against any named provider.
2. **Live provider verification** — a provider row is VERIFIED, PARTIAL, or
   NOT-RUN and links only to committed evidence for that real endpoint.

The generator rejects missing/out-of-tree evidence links and refuses a live
claim without evidence. NOT-RUN is never converted into a pass.

"""


class MatrixInputError(ValueError):
    pass


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise MatrixInputError(f"{path}: cannot load JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise MatrixInputError(f"{path}: top level must be an object")
    return value


def cell(value: Any) -> str:
    """Render untrusted source text as one Markdown table cell."""
    return str(value).replace("\r", " ").replace("\n", " ").replace("|", "\\|").strip()


def checked_doc_link(href: Any, docs_root: Path = DOCS) -> str:
    if not isinstance(href, str) or not href or "\\" in href:
        raise MatrixInputError(f"invalid evidence href: {href!r}")
    pure = PurePosixPath(href)
    if not pure.parts or pure.is_absolute() or ".." in pure.parts or pure.parts[0] in {"http:", "https:"}:
        raise MatrixInputError(f"evidence href must stay under docs/: {href}")
    target = (docs_root / Path(*pure.parts)).resolve()
    try:
        target.relative_to(docs_root.resolve())
    except ValueError as exc:
        raise MatrixInputError(f"evidence href escapes docs/: {href}") from exc
    if not target.is_file():
        raise MatrixInputError(f"evidence href does not exist: {href}")
    return pure.as_posix()


def suite_sections() -> str:
    parts: list[str] = []
    files = sorted(EVIDENCE.glob("compliance-summary-*.json"))
    if not files:
        raise MatrixInputError("no compliance summary files found")
    for path in files:
        data = load_json(path)
        suite = data.get("suite")
        sha = data.get("ci_sha")
        scenarios = data.get("scenarios")
        if not isinstance(suite, str) or not suite:
            raise MatrixInputError(f"{path}: missing suite")
        if not isinstance(sha, str) or not re.fullmatch(r"[0-9a-f]{40}", sha):
            raise MatrixInputError(f"{path}: ci_sha must be a 40-char lowercase SHA")
        if not isinstance(scenarios, list) or not scenarios:
            raise MatrixInputError(f"{path}: scenarios must be a non-empty array")
        if data.get("total") != len(scenarios):
            raise MatrixInputError(f"{path}: total does not match scenario count")
        rows = ["| Scenario | Result |", "|---|---|"]
        for scenario in scenarios:
            if not isinstance(scenario, dict) or not isinstance(scenario.get("pass"), bool):
                raise MatrixInputError(f"{path}: malformed scenario")
            result = "PASS" if scenario["pass"] else "**FAIL**"
            rows.append(f"| {cell(scenario.get('scenario', '?'))} | {result} |")
        rel = path.relative_to(ROOT).as_posix()
        parts.append(
            f"## Shared mock suite `{cell(suite)}`\n\n"
            f"CI commit `{sha}` · {len(scenarios)} scenarios · "
            f"evidence: [`{rel}`](evidence/{path.name})\n\n"
            + "\n".join(rows)
            + "\n"
        )
    return "\n".join(parts)


def validate_provider(provider: Any, docs_root: Path = DOCS) -> dict[str, Any]:
    if not isinstance(provider, dict):
        raise MatrixInputError("provider row must be an object")
    required = ("name", "preset_id", "endpoint", "live_status", "live_verification")
    for key in required:
        if not isinstance(provider.get(key), str) or not provider[key].strip():
            raise MatrixInputError(f"provider row missing non-empty {key}")
    status = provider["live_status"]
    if status not in VALID_STATUSES:
        raise MatrixInputError(f"{provider['preset_id']}: invalid live_status {status}")
    evidence = provider.get("live_evidence")
    if not isinstance(evidence, list):
        raise MatrixInputError(f"{provider['preset_id']}: live_evidence must be an array")
    if status == "NOT-RUN" and evidence:
        raise MatrixInputError(f"{provider['preset_id']}: NOT-RUN must not carry pass-like evidence")
    if status != "NOT-RUN" and not evidence:
        raise MatrixInputError(f"{provider['preset_id']}: {status} requires live evidence")
    checked: list[dict[str, str]] = []
    for item in evidence:
        if not isinstance(item, dict) or not isinstance(item.get("label"), str):
            raise MatrixInputError(f"{provider['preset_id']}: malformed evidence item")
        label = cell(item["label"]).replace("[", "\\[").replace("]", "\\]")
        checked.append({"label": label, "href": checked_doc_link(item.get("href"), docs_root)})
    return {**provider, "live_evidence": checked}


def provider_section() -> str:
    source = load_json(SOURCES)
    providers = source.get("providers")
    if not isinstance(providers, list) or not providers:
        raise MatrixInputError("providers must be a non-empty array")
    rows = [
        "| Provider | Preset id | Endpoint | Shared mock contract | Live status | Live verification |",
        "|---|---|---|---|---|---|",
    ]
    seen: set[str] = set()
    for raw in providers:
        provider = validate_provider(raw)
        preset_id = provider["preset_id"]
        if preset_id in seen:
            raise MatrixInputError(f"duplicate preset_id: {preset_id}")
        seen.add(preset_id)
        evidence = " ".join(
            f"[{item['label']}]({item['href']})" for item in provider["live_evidence"]
        )
        detail = cell(provider["live_verification"])
        live = f"{detail} {evidence}".strip()
        rows.append(
            f"| {cell(provider['name'])} | `{cell(preset_id)}` | "
            f"{cell(provider['endpoint'])} | shared 4a/4b only (not provider-specific) | "
            f"**{provider['live_status']}** | {live} |"
        )
    return "## Per-provider evidence status\n\n" + "\n".join(rows) + "\n"


def render() -> str:
    return HEADER + suite_sections() + "\n" + provider_section()


def main() -> int:
    try:
        body = render()
        if "--check" in sys.argv:
            current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
            if current != body:
                print(f"STALE: {OUT} — run scripts/gen_compat_matrix.py", file=sys.stderr)
                return 1
            print("fresh")
            return 0
        OUT.write_text(body, encoding="utf-8", newline="\n")
        print(f"wrote {OUT}")
        return 0
    except MatrixInputError as exc:
        print(f"COMPAT MATRIX INPUT ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
